Repository YaruG1022/WSU-SU21-CPTS322-Project, pull requests merged in 2024-06, with the labels that each got.

#6 Interface pull request
  Documentation/TeamNine_Team_Inventory.docx
  README.md
  src/module1.py
  src/static/StyleSheet1.css
  src/static/js/jquery-3.7.1.min.js
  src/static/js/navbar.js
  src/template/UserAccount.html
  src/template/donation.html
  src/template/homepage.html
  src/template/inventory.html
  src/template/report.html
  src/template/transaction.html
Labels: enhancement

#9 Merge backend login system commits into main
  .gitignore
  src/app.py
  src/data/test.db
  src/init_app.py
  src/login_bp.py
  src/models.py
  src/static/style.css
  src/templates/index.html
  src/templates/login_check.html
  src/templates/login_form_test.html
  src/templates/signup_form_test.html
Labels: enhancement

#18 Add 2FA, Inventory management, Server configuration, and TLS encryption to frontend
  .gitignore
  README.md
  setup.py
  src/app.py
  src/certs/place certificates here.txt
  src/interface.py
  src/login_bp.py
  src/models.py
  src/report_bp.py
  src/server.ini
  src/server_utils.py
  src/static/StyleSheet1.css
  src/static/homepage_style.css
  src/static/img/default_item.jpg
  src/static/img/profiles/default_item.jpg
  src/static/js/menu.js
  src/static/js/navbar.js
  src/static/js/slideshow.js
  src/static/report_style.css
  src/templates/additem_form.html
  src/templates/base.html
  src/templates/donation.html
  src/templates/homepage.html
  src/templates/interface_base.html
  src/templates/inventory.html
  src/templates/itemlist_test.html
  src/templates/login_required.html
  src/templates/otp_check.html
  src/templates/otp_setup.html
  src/templates/report.html
  src/templates/transaction.html
  src/templates/user_account.html
Labels: enhancement

#19 Implemented report generating system and inventory management system
  src/app.py
  src/interface.py
  src/inventory_bp.py
  src/models2.py
  src/static/StyleSheet1.css
  src/static/inventory_style.css
  src/templates/interface_base.html
  src/templates/inventory.html
Labels: enhancement, points: 13, priority I

#20 Implement ordering system
  src/app.py
  src/interface.py
  src/models.py
  src/server_utils.py
  src/templates/add_order.html
  src/templates/donation.html
  src/templates/interface_base.html
  src/templates/orders.html
  src/templates/transaction.html
Labels: enhancement

#21 Backend rebase and small fixes
  src/app.py
  src/report_bp.py
  src/static/StyleSheet1.css
  src/templates/inventory.html
Labels: bug

#22 Merge main into backend
  README.md
  Sprint_Reports/sprint_report_2.md
Labels: bug
